baseURL = "https://portfolio.soyjoel.com/"
languageCode = "es-es"
title = "Bienvenido a mi Portfolio"
theme = "terminal"


[params]
  # El color principal (puede ser "orange", "red", "blue", "green", "pink")
  themeColor = "green"
  # Texto que aparece junto al cursor en el header
  terminalText = "root@hacker:~#"
  # Descripción para buscadores
  description = "Portafolio de Ciberseguridad, Writeups y Proyectos"
  # CSS 	
  customCSS = ["css/custom.css"]
  # Logo
  logoText = "Ghxstsec"
  logoHomeLinkText = "Ir al inicio"
  
[menu]
  [[menu.main]]
    name = "Sobre Mi"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Writeups"
    url = "/writeups"
    weight = 2
  [[menu.main]]
    name = "Proyectos"
    url = "/proyectos"
    weight = 3
  [[menu.main]]
    name = "Certificaciones"
    url = "/certificaciones"
    weight = 4
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 5
  
